
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yesyesapp"
version = "1.0.0"
description = "Yes Yes Click App"
authors = [{name = "sifatrabbioffice", email = "sifat@example.com"}]

[tool.briefcase]
project_name = "Yes Yes App"
bundle = "com.yesyesapp"
version = "1.0.0"
description = "Click to start game app"
sources = ["src"]

[tool.briefcase.app.yesyesapp]
formal_name = "Yes Yes App"
description = "Click game app"
bundle = "com.yesyesapp"
url = "https://github.com/sifatrabbioffice/yesyesapp"
author = "sifatrabbioffice"
author_email = "sifat@example.com"
# Mandatory for mobile icons/splash screens
icon = "src/yesyesapp/resources/yesyesapp"

[tool.briefcase.app.yesyesapp.windows]
requires = ["pygame>=2.1.0"]

[tool.briefcase.app.yesyesapp.iOS]
requires = [
    "pygame-ce>=2.3.2", # pygame-ce is often better supported for mobile backends
    "rubicon-objc",      # Essential for Python to communicate with iOS Objective-C APIs
]
supported_os_versions = "13.0"
# Info.plist specific requirements
info = {
    "ITSAppUsesNonExemptEncryption" = false,
    "UIInterfaceOrientation" = ["UIInterfaceOrientationPortrait"],
    "UILaunchStoryboardName" = "LaunchScreen"
}
